spring.application.name=quick-fix
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/quickfix
spring.datasource.username=josecisneros
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
jwt.secret=TadMW7aF+vSfbO7vGrh/3rhxvQBV5XRyeEoUgQtq0wbQLH2C1evyGBd+zBRGURQvLxGaO623RZ4Pt4ZAsyhddw==
#spring.datasource.url=jdbc:postgresql://${PSQL_HOST}:${PSQL_PORT}/quickfix
#spring.datasource.username=${PSQL_USER}
#spring.datasource.password= ${PSQL_PASSWORD}
